theme = "blowfish"
defaultContentLanguage = "zh-TW"
enableRobotsTXT = true
paginate = 20
summaryLength = 30
buildDrafts = false
buildFuture = false
googleAnalytics = "G-1EQR8Q81BW"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
